const C=window.IRISH_OPPORTUNITIES_CONFIG||{API_BASE_URL:'',FALLBACK_COUNTS:{competitions:268,programmes:345,scholarships:334},PAGE_SIZE:30};
const PAGE_SIZE=Math.max(12,Number(C.PAGE_SIZE)||30);
const preview={competitions:[{id:'C001',name:'Irish Mathematical Olympiad (IrMO)',provider:'Irish Mathematical Olympiad / Irish universities',subject:'Mathematics',status:'Available',schoolYears:'1st Year, 2nd Year, 3rd Year, TY, 5th Year, 6th Year',entry:'School / teacher',cost:'Free',competitionType:'Olympiad',competitionLevel:'International',registrationDeadline:'',firstRound:'14 September 2026',dateStatus:'Expected Based on Previous Years',url:'https://www.irmo.ie/',description:'Irish selection pathway for the International Mathematical Olympiad.'}],programmes:[{id:'P001',name:'STEM@Universi-TY – Friday On-Campus',provider:'Trinity Walton Club',subject:'STEM',status:'Open',schoolYears:'TY',tyEligible:'Yes',entry:'Direct student application',cost:'€980',opportunityType:'Academic Enrichment',county:'Dublin',location:'Trinity College Dublin',mode:'In-person',duration:'20 weeks',startDate:'2 October 2026',dateStatus:'Confirmed 2026/27',url:'https://www.tcd.ie/waltonclub/ty.php',description:'Twenty-week university STEM enrichment programme at Trinity College Dublin.'}],scholarships:[{id:'S001',name:'Naughton Scholarships',provider:'The Naughton Foundation',subject:'STEM',status:'Next cycle TBA',schoolYears:'6th Year / College entry',entry:'Direct application',awardValue:'€24,000 / €18,000 award',fundingType:'Scholarship',awardBasis:'Academic Merit',studyCountry:'Ireland',applicationDeadline:'2027 TBA',url:'https://www.thenaughtonfoundation.com/how-to-apply',description:'Scholarship for Leaving Certificate students progressing to eligible STEM degrees.'}]};
let data={competitions:[],programmes:[],scholarships:[]},upcoming=[],tab='home',teacher=false,visibleLimit=PAGE_SIZE,lastFiltered=[],saved=new Set(JSON.parse(localStorage.getItem('iao_saved')||'[]'));
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const canon=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const text=s=>String(s??'').trim();
function indexed(o){const m={};Object.entries(o||{}).forEach(([k,v])=>{if(v!==null&&v!==undefined&&String(v).trim()!=='')m[canon(k)]=v});return m}
function pick(o,idx,...keys){for(const k of keys){if(o&&o[k]!==undefined&&text(o[k]))return o[k];const v=idx[canon(k)];if(v!==undefined&&text(v))return v}return''}
function yes(v){return /^(yes|true|y|1)$/i.test(text(v))}
function guessKind(o,hint){const h=text(hint).toLowerCase();if(['competitions','programmes','scholarships'].includes(h))return h;const id=text(o?.id||o?.competitionId||o?.programmeId||o?.scholarshipId||o?.['Competition ID']||o?.['Programme ID']||o?.['Scholarship ID']).toUpperCase();return id.startsWith('P')?'programmes':id.startsWith('S')?'scholarships':'competitions'}
function mapRecord(o,kindHint){const idx=indexed(o),kind=guessKind(o,kindHint);const r={raw:o,kind};
 r.id=pick(o,idx,'id','competitionId','programmeId','scholarshipId','Competition ID','Programme ID','Scholarship ID');
 r.name=pick(o,idx,'name','competitionName','programmeName','scholarshipName','Competition Name','Programme Name','Scholarship Name','Competition','Programme');
 r.altName=pick(o,idx,'currentAlternativeName','Current / Alternative Name');
 r.provider=pick(o,idx,'provider','organiser','Provider','Organiser');r.providerType=pick(o,idx,'providerType','Provider Type');
 r.subject=pick(o,idx,'subject','Subject','Subject / Course','category','Category');r.subcategory=pick(o,idx,'subcategory','Subcategory');
 r.competitionType=pick(o,idx,'competitionType','Competition Type','Type');r.competitionLevel=pick(o,idx,'competitionLevel','Competition Level','Level');
 r.opportunityType=pick(o,idx,'opportunityType','Opportunity Type','Competition Type','Type');r.scope=pick(o,idx,'scope','Scope','Competition Level');
 r.programmeStatus=pick(o,idx,'programmeStatus','Programme Status');r.applicationStatus=pick(o,idx,'applicationStatus','Application Status');r.currentStatus=pick(o,idx,'currentStatus','Current Status','status','Status','Timing / Status');
 r.status=kind==='programmes'?(r.applicationStatus||r.programmeStatus||r.currentStatus):r.currentStatus;
 r.schoolYears=pick(o,idx,'schoolYears','eligibleIrishSchoolYears','applicantStage','Eligible Irish School Years','Eligible School Years','Applicant Stage');r.applicantStage=pick(o,idx,'applicantStage','Applicant Stage');
 r.minAge=pick(o,idx,'minimumAge','Minimum Age');r.maxAge=pick(o,idx,'maximumAge','Maximum Age');r.tyEligible=pick(o,idx,'transitionYearEligible','Transition Year Eligible?');
 r.entry=pick(o,idx,'entry','entryMethod','applicationRoute','accessType','Entry Method','Application Route','Access Type','How to Apply');r.applicationMethod=pick(o,idx,'applicationMethodPlatform','Application Method / Platform','registrationPlatform','Registration Platform','How to Apply');
 r.studentDirect=pick(o,idx,'studentCanApplyDirectly','studentCanRegisterDirectly','Student Can Apply Directly?','Student Can Register Directly?');r.schoolRegister=pick(o,idx,'schoolMustApplyNominate','schoolMustRegister','School Must Apply / Nominate?','School Must Register?');r.teacherRequired=pick(o,idx,'teacherCoordinatorRequired','Teacher / Coordinator Required?','Teacher / School Coordinator Required?');
 r.accessType=pick(o,idx,'accessType','Access Type');r.accessRestrictions=pick(o,idx,'accessRestrictions','Access Restrictions');
 r.county=pick(o,idx,'county','County');r.location=pick(o,idx,'locationVenue','Location / Venue','location','Location');r.mode=pick(o,idx,'deliveryMode','Delivery Mode');r.duration=pick(o,idx,'duration','Duration');r.residential=pick(o,idx,'residential','Residential?');r.places=pick(o,idx,'placesCapacity','Places / Capacity');r.selectivity=pick(o,idx,'selectivity','Selectivity');
 r.cost=pick(o,idx,'cost','Cost');r.costCategory=pick(o,idx,'costCategory','Cost Category');r.costSource=pick(o,idx,'costSource','Cost Source');r.costChecked=pick(o,idx,'costChecked','Cost Checked');r.costNotes=pick(o,idx,'costNotes','Cost Notes');
 r.category=pick(o,idx,'category','Category');r.studyCountry=pick(o,idx,'studyCountry','Study Country');r.studyInstitution=pick(o,idx,'studyInstitution','Study Institution');r.fundingType=pick(o,idx,'fundingType','Funding Type');r.awardBasis=pick(o,idx,'awardBasis','Award Basis');r.financialNeed=pick(o,idx,'financialNeedRequired','Financial Need Required?');r.awardValue=pick(o,idx,'awardValue','Award Value');r.coverage=pick(o,idx,'coverage','Coverage');r.entryCycle=pick(o,idx,'entryCycle','Entry / Cycle');
 r.applicationOpens=pick(o,idx,'applicationOpens','Application Opens','registrationOpens','Registration Opens');r.applicationDeadline=pick(o,idx,'applicationDeadline','Application Deadline','registrationDeadline','Registration Deadline');r.submissionDeadline=pick(o,idx,'submissionDeadline','Submission Deadline');
 r.firstRound=pick(o,idx,'firstPreliminaryRound','First / Preliminary Round');r.regionalRound=pick(o,idx,'regionalRound','Regional Round');r.nationalRound=pick(o,idx,'nationalRound','National Round');r.nationalFinal=pick(o,idx,'nationalFinal','National Final');r.internationalFinal=pick(o,idx,'internationalRoundFinal','International Round / Final');
 r.startDate=pick(o,idx,'programmeStartDate','competitionStartDate','Programme Start Date','Programme Start','Competition Start Date','Next Competition Date','date','Date');r.endDate=pick(o,idx,'programmeEndDate','competitionEndDate','Programme End Date','Competition End Date');r.resultsDate=pick(o,idx,'resultsDate','Results Date');r.additionalDates=pick(o,idx,'additionalImportantDates','Additional Important Dates');r.dateStatus=pick(o,idx,'dateStatus','Date Status');
 r.url=pick(o,idx,'officialWebsite','officialLink','Official Website','Official Link','url');r.currentPage=pick(o,idx,'currentYearPage','currentIntakePage','Current Year Page','Current Intake Page');
 r.description=pick(o,idx,'keyFeaturesDescription','Key Features / Description','description','Description');r.eligibility=pick(o,idx,'eligibilityRestrictions','Eligibility / Restrictions','eligibilityNotes','Eligibility Notes','Age / Key Eligibility');r.eligibilitySource=pick(o,idx,'eligibilitySource','Eligibility Source');r.eligibilityChecked=pick(o,idx,'eligibilityChecked','Eligibility Checked');
 r.monitoringSource=pick(o,idx,'monitoringSource','Monitoring Source');r.lastVerified=pick(o,idx,'lastVerified','Last Verified','costChecked','Cost Checked');r.verificationConfidence=pick(o,idx,'verificationConfidence','Verification Confidence');r.searchTags=pick(o,idx,'searchTags','Search Tags');r.finderEligible=pick(o,idx,'finderEligible','Finder Eligible?');
 if(kind==='scholarships'){r.cost=r.awardValue||r.cost;r.entry=r.entry||pick(o,idx,'applicationRoute','Application Route');r.schoolYears=r.schoolYears||r.applicantStage;r.description=r.description||r.eligibility;r.opportunityType=r.fundingType||r.category}
 r.geography=kind==='scholarships'?(r.studyCountry||r.studyInstitution):kind==='programmes'?(r.county||r.scope||r.location):(r.competitionLevel||r.scope);
 r.searchText=Object.values(o||{}).filter(v=>['string','number','boolean'].includes(typeof v)).join(' ')+' '+Object.values(r).filter(v=>typeof v==='string').join(' ');
 return r}
function jsonp(url){return new Promise((res,rej)=>{const cb='iao_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(()=>done(new Error('timeout')),15000);function done(e,v){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}s.remove();e?rej(e):res(v)}window[cb]=r=>r&&r.ok?done(null,r.data):done(new Error(r?.error||'API error'));s.onerror=()=>done(new Error('network'));s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.head.appendChild(s)})}
