function find(id){return allData().find(x=>x.id===id)||upcoming.find(x=>x.id===id)}
function save(id){if(!id)return;saved.has(id)?saved.delete(id):saved.add(id);localStorage.setItem('iao_saved',JSON.stringify([...saved]));refreshSaved();if(tab!=='home')renderFinder();else renderUpcoming()}
function refreshSaved(){$('savedCount').textContent=saved.size}
function fact(label,value){return value?'<div class="fact"><small>'+esc(label)+'</small><span>'+esc(value)+'</span></div>':''}
function sourceLink(label,url){return url?'<a class="source-link" href="'+esc(url)+'" target="_blank" rel="noopener"><strong>'+esc(label)+'</strong><br>'+esc(url)+'</a>':''}
function detailFields(x){if(x.kind==='programmes')return[['Eligibility',x.schoolYears],['TY eligible',x.tyEligible],['Minimum age',x.minAge],['Maximum age',x.maxAge],['Opportunity type',x.opportunityType],['Scope',x.scope],['County',x.county],['Location / venue',x.location],['Delivery mode',x.mode],['Duration',x.duration],['Residential',x.residential],['Places / capacity',x.places],['Selectivity',x.selectivity],['Application status',x.applicationStatus],['Programme status',x.programmeStatus],['Access type',x.accessType],['Access restrictions',x.accessRestrictions],['Application route',x.entry],['Application method',x.applicationMethod],['Student can apply directly',x.studentDirect],['School nomination/application',x.schoolRegister],['Teacher/coordinator required',x.teacherRequired],['Cost',x.cost],['Cost category',x.costCategory],['Application opens',x.applicationOpens],['Application deadline',x.applicationDeadline],['Programme starts',x.startDate],['Programme ends',x.endDate],['Date status',x.dateStatus],['Additional dates',x.additionalDates]];if(x.kind==='scholarships')return[['Applicant stage',x.applicantStage],['Study country',x.studyCountry],['Study institution',x.studyInstitution],['Funding type',x.fundingType],['Award basis',x.awardBasis],['Subject / course',x.subject],['Financial need required',x.financialNeed],['Application route',x.entry],['Award value',x.awardValue],['Coverage',x.coverage],['Application deadline',x.applicationDeadline],['Entry / cycle',x.entryCycle],['Current status',x.status]];return[['Eligible school years',x.schoolYears],['Minimum age',x.minAge],['Maximum age',x.maxAge],['TY eligible',x.tyEligible],['Competition type',x.competitionType],['Competition level',x.competitionLevel],['Entry method',x.entry],['Registration platform',x.applicationMethod],['Student can register directly',x.studentDirect],['School must register',x.schoolRegister],['Teacher/coordinator required',x.teacherRequired],['Cost',x.cost],['Cost category',x.costCategory],['Registration opens',x.applicationOpens],['Registration deadline',x.applicationDeadline],['Submission deadline',x.submissionDeadline],['First / preliminary round',x.firstRound],['Regional round',x.regionalRound],['National round',x.nationalRound],['National final',x.nationalFinal],['International round / final',x.internationalFinal],['Competition starts',x.startDate],['Competition ends',x.endDate],['Results date',x.resultsDate],['Date status',x.dateStatus],['Additional dates',x.additionalDates]]}
function details(id){const x=find(id);if(!x)return;$('dtype').textContent=typeLabel(x.kind)+(x.id?' · '+x.id:'');$('dtitle').textContent=x.name;$('dprovider').textContent=x.provider||'';const fields=detailFields(x).filter(([,v])=>text(v));const sources=[sourceLink('Official source',x.url),sourceLink('Current cycle / intake page',x.currentPage),sourceLink('Eligibility source',x.eligibilitySource),sourceLink('Cost source',x.costSource),sourceLink('Monitoring source',x.monitoringSource)].filter(Boolean).join('');$('dbody').innerHTML=(x.description?'<div class="detail-section"><h3>About this opportunity</h3><p>'+esc(x.description)+'</p></div>':'')+(x.eligibility?'<div class="detail-section"><h3>Eligibility / restrictions</h3><p>'+esc(x.eligibility)+'</p></div>':'')+'<div class="detail-section"><h3>Key details</h3><div class="grid">'+fields.map(([l,v])=>fact(l,v)).join('')+'</div></div>'+(x.costNotes?'<div class="detail-section"><h3>Cost notes</h3><p>'+esc(x.costNotes)+'</p></div>':'')+'<div class="detail-section"><h3>Verification</h3><div class="grid">'+fact('Last verified',x.lastVerified)+fact('Eligibility checked',x.eligibilityChecked)+fact('Cost checked',x.costChecked)+fact('Confidence',x.verificationConfidence)+fact('Date status',x.dateStatus)+'</div></div>'+(sources?'<div class="detail-section"><h3>Sources</h3><div class="source-list">'+sources+'</div></div>':'');$('dialog').showModal();history.replaceState(null,'',urlFor({id:x.id}))}
function renderUpcoming(){const items=(upcoming.length?upcoming:[data.competitions[0],data.programmes[0],data.scholarships[0]].filter(Boolean)).slice(0,3);$('homeUpcoming').innerHTML=items.length?items.map(card).join(''):'<div class="empty">Upcoming data is loading.</div>'}
function activeFilterPairs(){const pairs=[];if($('q').value)pairs.push(['Search',$('q').value]);const labels={typeFilter:'Group',schoolYear:'School year',subject:'Subject',geography:'Geography',costFilter:'Cost',statusFilter:'Status',mode:'Mode',opportunityType:'Type',fundingType:'Funding',awardBasis:'Award basis',entryRoute:'Entry route',deadline:'Deadline'};for(const id of filterIds){const el=$(id);if(el?.value&&!el.classList.contains('hide'))pairs.push([labels[id],el.options?.[el.selectedIndex]?.text||el.value])}return pairs}
function renderActiveFilters(){const pairs=activeFilterPairs();$('activeFilters').innerHTML=pairs.map(([a,b])=>'<span class="filter-chip">'+esc(a)+': '+esc(b)+'</span>').join('')}
function clearAll(){ $('q').value='';for(const id of filterIds){const el=$(id);if(el)el.value=''}$('sort').value='relevance';visibleLimit=PAGE_SIZE;renderFinder() }
function applyUrl(){const p=new URLSearchParams(location.search),t=p.get('tab')||C.DEFAULT_TAB||'home';if(p.get('q'))$('q').value=p.get('q');for(const id of filterIds)if(p.get(id))$(id).dataset.pending=p.get(id);if(p.get('sort'))$('sort').value=p.get('sort');setTab(['home','all','competitions','programmes','scholarships','upcoming','saved'].includes(t)?t:'home',{updateUrl:false});for(const id of filterIds){const el=$(id),v=el.dataset.pending;if(v){if([...el.options].some(o=>o.value===v))el.value=v;delete el.dataset.pending}}if(tab!=='home')renderFinder();history.replaceState(null,'',urlFor());if(p.get('id'))setTimeout(()=>details(p.get('id')),80)}
document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t)setTab(t.dataset.tab);const s=e.target.closest('[data-save]');if(s){e.stopPropagation();save(s.dataset.save)}const d=e.target.closest('[data-detail]');if(d)details(d.dataset.detail);const p=e.target.closest('[data-preset]');if(p){clearAll();if(p.dataset.preset==='ty'){setTab('programmes');$('schoolYear').value='TY'}if(p.dataset.preset==='free')$('costFilter').value='free';if(p.dataset.preset==='international'){setTab('all');const opt=[...$('geography').options].find(o=>/international/i.test(o.value));if(opt)$('geography').value=opt.value;else $('q').value='international'}if(p.dataset.preset==='closing'){setTab('all');$('deadline').value='30'}visibleLimit=PAGE_SIZE;renderFinder()}});
$('heroForm').addEventListener('submit',e=>{e.preventDefault();clearAll();$('q').value=$('heroSearch').value.trim();setTab('all')});
['q','typeFilter','schoolYear','subject','geography','costFilter','statusFilter','mode','opportunityType','fundingType','awardBasis','entryRoute','deadline','sort'].forEach(id=>$(id).addEventListener(id==='q'?'input':'change',()=>{visibleLimit=PAGE_SIZE;renderFinder()}));
$('clearFilters').onclick=clearAll;$('clearTop').onclick=clearAll;$('more').onclick=()=>{visibleLimit+=PAGE_SIZE;renderResults(baseForTab())};
$('teacherBtn').onclick=()=>{teacher=!teacher;$('teacherPanel').classList.toggle('on',teacher);$('teacherBtn').textContent=teacher?'Teacher mode ✓':'Teacher mode'};
$('share').onclick=async()=>{const u=location.origin+urlFor();try{await navigator.clipboard.writeText(u);$('share').textContent='Copied!';setTimeout(()=>$('share').textContent='Share view',1200)}catch{prompt('Copy this link:',u)}};
$('copyIds').onclick=async()=>{const lines=lastFiltered.slice(0,100).map(x=>[x.name,x.provider,x.url].filter(Boolean).join(' — ')).join('\n');try{await navigator.clipboard.writeText(lines);$('copyIds').textContent='Copied!';setTimeout(()=>$('copyIds').textContent='Copy shortlist',1200)}catch{prompt('Copy shortlist:',lines)}};
$('closeDialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>history.replaceState(null,'',urlFor()));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
load();
