async function load(){let live=false;setLoading(true);if(C.API_BASE_URL){try{const b=await jsonp(C.API_BASE_URL+'?api=bootstrap'),counts=b?.counts||C.FALLBACK_COUNTS;setCounts(counts);const keys=['competitions','programmes','scholarships'];const responses=await Promise.all(keys.map(k=>jsonp(C.API_BASE_URL+'?api=dataset&kind='+k)));keys.forEach((k,i)=>{const r=responses[i],arr=Array.isArray(r)?r:(r?.records||r?.items||[]);data[k]=arr.map(x=>mapRecord(x,k))});const u=await jsonp(C.API_BASE_URL+'?api=upcoming');upcoming=(Array.isArray(u)?u:(u?.records||u?.items||[])).map(x=>mapRecord(x,x.kind||x.type));live=true}catch(e){console.warn('Live data unavailable',e)}}if(!live){for(const k in preview)data[k]=preview[k].map(x=>mapRecord(x,k));upcoming=[data.competitions[0],data.programmes[0],data.scholarships[0]].filter(Boolean);$('status').textContent='Frontend preview'}else{$('status').textContent='Live data';$('status').style.background='#2b7b6b'}setLoading(false);renderUpcoming();refreshSaved();applyUrl()}
function setLoading(on){document.body.classList.toggle('loading',on);if(on&&$('results'))$('results').innerHTML='<div class="skeleton"></div><div class="skeleton"></div>'}
function setCounts(c){const a=+c?.competitions||+C.FALLBACK_COUNTS?.competitions||268,b=+c?.programmes||+C.FALLBACK_COUNTS?.programmes||345,d=+c?.scholarships||+C.FALLBACK_COUNTS?.scholarships||334;$('cc').textContent=a;$('pc').textContent=b;$('sc').textContent=d;$('total').textContent=a+b+d}
function baseForTab(){if(tab==='all')return allData();if(tab==='saved')return allData().filter(x=>saved.has(x.id));if(tab==='upcoming')return upcoming;return data[tab]||[]}
function allData(){const seen=new Set(),out=[];for(const x of [...data.competitions,...data.programmes,...data.scholarships])if(x?.id&&!seen.has(x.id)){seen.add(x.id);out.push(x)}return out}
function setTab(t,{updateUrl=true}={}){tab=t;visibleLimit=PAGE_SIZE;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$('home').classList.toggle('hide',t!=='home');$('finder').classList.toggle('hide',t==='home');if(t!=='home')renderFinder();if(updateUrl)history.replaceState(null,'',urlFor());scrollTo({top:0,behavior:'smooth'})}
const filterIds=['typeFilter','schoolYear','subject','geography','costFilter','statusFilter','mode','opportunityType','fundingType','awardBasis','entryRoute','deadline'];
function urlFor(extra={}){const p=new URLSearchParams();if(tab!=='home')p.set('tab',tab);if($('q')?.value)p.set('q',$('q').value);for(const id of filterIds){const el=$(id);if(el?.value)p.set(id,el.value)}if($('sort')?.value&&$('sort').value!=='relevance')p.set('sort',$('sort').value);if(extra.id)p.set('id',extra.id);return location.pathname+(p.toString()?'?'+p:'')}
function titleFor(){if(tab==='all')return['All opportunities','Search competitions, programmes and funding together.'];if(tab==='saved')return['Saved opportunities','Your shortlist is stored on this device.'];if(tab==='upcoming')return['Upcoming opportunities','A combined feed of confirmed and expected dates from the live master.'];if(tab==='competitions')return['Competitions','Search olympiads, contests, projects, writing, debating, coding, arts and more.'];if(tab==='programmes')return['Programmes','Search TY, enrichment, work experience, research, summer schools and courses.'];return['Scholarships & funding','Search scholarships, bursaries, grants, fee support and international awards.']}
function renderFinder(){const base=baseForTab(),[title,desc]=titleFor();$('title').textContent=title;$('desc').textContent=desc;populateFilters(base);applyFilterVisibility(base);renderResults(base)}
function unique(arr,field){return[...new Set(arr.map(x=>text(x[field])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'}))}
function fillSelect(id,vals,label){const el=$(id),old=el.value;el.innerHTML='<option value="">'+esc(label)+'</option>'+vals.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');if(vals.includes(old))el.value=old}
function geographyOptions(arr){const vals=[];arr.forEach(x=>{if(x.kind==='scholarships'&&x.studyCountry)vals.push(x.studyCountry);else if(x.kind==='programmes'){if(x.county)vals.push(x.county);if(x.scope&&x.scope!==x.county)vals.push(x.scope);if(/online/i.test(x.mode||x.location))vals.push('Online')}else if(x.competitionLevel)vals.push(x.competitionLevel)});return[...new Set(vals.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function entryOptions(arr){return[...new Set(arr.map(x=>text(x.entry||x.applicationMethod)).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function populateFilters(base){fillSelect('subject',unique(base,'subject'),'All subjects');fillSelect('geography',geographyOptions(base),'Anywhere');fillSelect('mode',unique(base.filter(x=>x.kind==='programmes'),'mode'),'Any mode');fillSelect('opportunityType',unique(base,'opportunityType'),'Any opportunity type');fillSelect('fundingType',unique(base.filter(x=>x.kind==='scholarships'),'fundingType'),'Any funding type');fillSelect('awardBasis',unique(base.filter(x=>x.kind==='scholarships'),'awardBasis'),'Any award basis');fillSelect('entryRoute',entryOptions(base),'Any entry route')}
function applyFilterVisibility(base){const kinds=new Set(base.map(x=>x.kind));$('typeFilter').classList.toggle('hide',['competitions','programmes','scholarships'].includes(tab));$('modeWrap').classList.toggle('hide',!kinds.has('programmes'));$('fundingWrap').classList.toggle('hide',!kinds.has('scholarships'));$('awardWrap').classList.toggle('hide',!kinds.has('scholarships'));$('opportunityWrap').classList.toggle('hide',!base.some(x=>x.opportunityType));$('filterSummary').textContent=kinds.size===1?'Type-specific filters active':'Combined filters across all opportunity groups'}
function norm(s){return text(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function queryTokens(q){const raw=norm(q).split(/\s+/).filter(Boolean),aliases={ty:['ty','transition year'],scholarship:['scholarship','funding','award'],funding:['funding','scholarship','bursary','grant','award'],online:['online','virtual','remote'],free:['free','no cost','€0'],maths:['maths','mathematics'],math:['math','maths','mathematics']};return raw.map(t=>aliases[t]||[t])}
function matchesQuery(x,q){if(!q)return true;const hay=norm(x.searchText);return queryTokens(q).every(group=>group.some(t=>hay.includes(norm(t))))}
function relevanceScore(x,q){if(!q)return 0;const n=norm(x.name),p=norm(x.provider),s=norm(x.subject),tags=norm(x.searchTags),desc=norm(x.description+' '+x.eligibility),tokens=norm(q).split(/\s+/).filter(Boolean);let score=0;for(const t of tokens){if(n===t)score+=20;if(n.startsWith(t))score+=12;if(n.includes(t))score+=9;if(s.includes(t))score+=6;if(p.includes(t))score+=5;if(tags.includes(t))score+=4;if(desc.includes(t))score+=2}return score}
function statusClass(x){const s=norm([x.status,x.programmeStatus,x.applicationStatus].join(' '));if(/automatic|no separate application|no student application/.test(s))return'automatic';if(/closed|ended|inactive|passed/.test(s))return'closed';if(/open|available|active|accepting/.test(s))return'open';if(/upcoming|expected|tba|next cycle|planned|future/.test(s))return'upcoming';return''}
function costClass(x){if(x.kind==='scholarships')return'funding';const s=norm(x.cost+' '+x.costCategory);if(!s)return'unknown';if(/free|no cost|€0|eur 0/.test(s))return'free';return'paid'}
function includesLoose(value,needle){return!needle||norm(value).includes(norm(needle))}
function schoolMatch(x,v){if(!v)return true;const s=norm(x.schoolYears+' '+x.applicantStage+' '+x.tyEligible);if(v==='TY')return/\bty\b|transition year/.test(s)||yes(x.tyEligible);if(v==='College entry')return/college entry|undergraduate|6th year/.test(s);return s.includes(norm(v))}
const MONTHS='January February March April May June July August September October November December';
function parseDateValue(v){if(!v)return null;const s=text(v);let d=new Date(s);if(!Number.isNaN(d.getTime()))return d;const m=s.match(new RegExp('(\\d{1,2})\\s+('+MONTHS.replace(/ /g,'|')+')\\s+(20\\d{2})','i'));if(m){d=new Date(m[2]+' '+m[1]+', '+m[3]);if(!Number.isNaN(d.getTime()))return d}const iso=s.match(/(20\d{2})[-\/]([01]?\d)[-\/]([0-3]?\d)/);if(iso){d=new Date(+iso[1],+iso[2]-1,+iso[3]);if(!Number.isNaN(d.getTime()))return d}return null}
function dateCandidates(x){const out=[];const add=(label,v)=>{const d=parseDateValue(v);if(d)out.push({label,value:v,date:d})};if(x.kind==='competitions'){add('Registration deadline',x.applicationDeadline);add('Submission deadline',x.submissionDeadline);add('First round',x.firstRound);add('Regional round',x.regionalRound);add('National round',x.nationalRound);add('National final',x.nationalFinal);add('International final',x.internationalFinal);add('Competition starts',x.startDate);add('Competition ends',x.endDate);add('Results',x.resultsDate)}else if(x.kind==='programmes'){add('Application deadline',x.applicationDeadline);add('Programme starts',x.startDate);add('Programme ends',x.endDate)}else add('Application deadline',x.applicationDeadline);return out.sort((a,b)=>a.date-b.date)}
function nextDate(x){const now=new Date();now.setHours(0,0,0,0);return dateCandidates(x).find(c=>c.date>=now)||dateCandidates(x)[0]||null}
function deadlineMatch(x,v){if(!v)return true;const nd=nextDate(x);if(v==='known')return!!nd;if(!nd)return false;const now=new Date();now.setHours(0,0,0,0);const days=(nd.date-now)/86400000;return days>=0&&days<=Number(v)}
function filterRecords(base){let arr=[...base],q=$('q').value.trim();if(tab==='all'||tab==='saved'||tab==='upcoming'){const tf=$('typeFilter').value;if(tf)arr=arr.filter(x=>x.kind===tf)}if(q)arr=arr.filter(x=>matchesQuery(x,q));const sub=$('subject').value;if(sub)arr=arr.filter(x=>x.subject===sub);const sy=$('schoolYear').value;if(sy)arr=arr.filter(x=>schoolMatch(x,sy));const geo=$('geography').value;if(geo)arr=arr.filter(x=>includesLoose(x.geography+' '+x.studyCountry+' '+x.county+' '+x.scope+' '+x.location+' '+x.competitionLevel,geo));const cost=$('costFilter').value;if(cost)arr=arr.filter(x=>costClass(x)===cost);const st=$('statusFilter').value;if(st)arr=arr.filter(x=>statusClass(x)===st);const mode=$('mode').value;if(mode)arr=arr.filter(x=>x.mode===mode);const ot=$('opportunityType').value;if(ot)arr=arr.filter(x=>x.opportunityType===ot);const ft=$('fundingType').value;if(ft)arr=arr.filter(x=>x.fundingType===ft);const ab=$('awardBasis').value;if(ab)arr=arr.filter(x=>x.awardBasis===ab);const er=$('entryRoute').value;if(er)arr=arr.filter(x=>(x.entry||x.applicationMethod)===er);const dh=$('deadline').value;if(dh)arr=arr.filter(x=>deadlineMatch(x,dh));const sort=$('sort').value;if(sort==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));else if(sort==='verified')arr.sort((a,b)=>(parseDateValue(b.lastVerified)?.getTime()||0)-(parseDateValue(a.lastVerified)?.getTime()||0));else if(sort==='date'||(!q&&sort==='relevance'))arr.sort((a,b)=>(nextDate(a)?.date?.getTime()||Infinity)-(nextDate(b)?.date?.getTime()||Infinity));else if(sort==='relevance'&&q)arr.sort((a,b)=>relevanceScore(b,q)-relevanceScore(a,q)||a.name.localeCompare(b.name));return arr}
function renderResults(base){const arr=filterRecords(base);lastFiltered=arr;$('resultCount').textContent=arr.length+' opportunit'+(arr.length===1?'y':'ies');$('context').textContent=tab==='all'?'across competitions, programmes and funding':'';$('results').innerHTML=arr.length?arr.slice(0,visibleLimit).map(card).join(''):'<div class="empty"><strong>No opportunities match these filters.</strong><br>Try clearing one or more filters or broadening your search.</div>';$('moreWrap').classList.toggle('hide',arr.length<=visibleLimit);renderActiveFilters();history.replaceState(null,'',urlFor())}
function typeLabel(k){return k==='competitions'?'Competition':k==='programmes'?'Programme':'Funding'}
function displayStatus(x){return x.status||x.programmeStatus||x.applicationStatus||'Check current status'}
function primaryFacts(x){const nd=nextDate(x);if(x.kind==='programmes')return[['Eligible',x.schoolYears||'See official page'],['Location',x.location||x.county||x.scope||'See details'],['Mode / duration',[x.mode,x.duration].filter(Boolean).join(' · ')||'See details'],[nd?.label||'Next date',nd?.value||x.startDate||'TBA'],['Access',x.accessRestrictions||x.accessType||x.entry||'See details'],['Cost',x.cost||'See official page']];if(x.kind==='scholarships')return[['Applicant stage',x.applicantStage||x.schoolYears||'See official page'],['Study country',x.studyCountry||'See details'],['Funding type',[x.fundingType,x.awardBasis].filter(Boolean).join(' · ')||'See details'],['Deadline',x.applicationDeadline||'TBA'],['Application route',x.entry||'See details'],['Award value',x.awardValue||x.coverage||'See official page']];return[['Eligible',x.schoolYears||'See official page'],['Level / format',[x.competitionLevel,pick(x.raw,indexed(x.raw),'Individual / Team / Both','Individual / Team')].filter(Boolean).join(' · ')||'See details'],['Entry',x.entry||'See official page'],[nd?.label||'Next date',nd?.value||'TBA'],['Type',x.competitionType||x.opportunityType||'Competition'],['Cost',x.cost||'See official page']]}
function card(x){const facts=primaryFacts(x).slice(0,4),status=statusClass(x),dateExpected=/expected|tba|previous years|partially/i.test(x.dateStatus||'');return '<article class="card"><div class="card-top"><div><span class="type">'+esc(typeLabel(x.kind))+(x.id?' · '+esc(x.id):'')+'</span><h3>'+esc(x.name||'Untitled opportunity')+'</h3><p class="provider">'+esc(x.provider||'')+'</p></div><button class="heart '+(saved.has(x.id)?'on':'')+'" data-save="'+esc(x.id)+'" aria-label="'+(saved.has(x.id)?'Remove from saved':'Save opportunity')+'">'+(saved.has(x.id)?'♥':'♡')+'</button></div><div class="badges">'+(x.subject?'<span class="badge sub">'+esc(x.subject)+'</span>':'')+(costClass(x)==='free'?'<span class="badge free">Free</span>':'')+'<span class="badge '+(status==='closed'?'closed':'')+'">'+esc(displayStatus(x))+'</span>'+(dateExpected?'<span class="badge expected">Dates expected / provisional</span>':'')+'</div><div class="facts">'+facts.map(f=>'<div class="fact"><small>'+esc(f[0])+'</small><span>'+esc(f[1]||'—')+'</span></div>').join('')+'</div>'+(x.description||x.eligibility?'<p class="summary">'+esc(x.description||x.eligibility)+'</p>':'')+'<div class="actions"><button class="detail" data-detail="'+esc(x.id)+'">Details</button>'+(x.url?'<a class="official" href="'+esc(x.url)+'" target="_blank" rel="noopener">Official page ↗</a>':'')+'</div></article>'}
