/* Stage 3: richer opportunity details, provenance, related opportunities and anonymous feedback. */
const relatedCache=new Map();
function s3Date(v){return parseDateValue(v)||calDate?.(v)||null}
function s3Freshness(x){const raw=x.lastVerified||x.eligibilityChecked||x.costChecked||'';const d=s3Date(raw);if(!d)return{label:'Verification date not published',cls:'watch',raw};const now=new Date();now.setHours(0,0,0,0);d.setHours(0,0,0,0);const days=Math.max(0,Math.round((now-d)/86400000));if(days<=14)return{label:days===0?'Verified today':'Verified '+days+' day'+(days===1?'':'s')+' ago',cls:'fresh',raw};if(days<=60)return{label:'Verified '+days+' days ago',cls:'watch',raw};return{label:'Last verified '+raw,cls:'stale',raw}}
function s3DirectUrl(x){const u=new URL(location.pathname,location.origin);u.searchParams.set('tab','all');u.searchParams.set('id',x.id);return u.toString()}
function s3Copy(textValue,button,doneLabel){return navigator.clipboard?.writeText(textValue).then(()=>{if(button){const old=button.textContent;button.textContent=doneLabel||'Copied!';setTimeout(()=>button.textContent=old,1300)}}).catch(()=>prompt('Copy this:',textValue))}
function s3Timeline(x){const items=[];const add=(label,value)=>{if(text(value))items.push([label,value])};if(x.kind==='competitions'){add('Registration opens',x.applicationOpens);add('Registration deadline',x.applicationDeadline);add('Submission deadline',x.submissionDeadline);add('First / preliminary round',x.firstRound);add('Regional round',x.regionalRound);add('National round',x.nationalRound);add('National final',x.nationalFinal);add('International final',x.internationalFinal);add('Competition starts',x.startDate);add('Competition ends',x.endDate);add('Results',x.resultsDate)}else if(x.kind==='programmes'){add('Applications open',x.applicationOpens);add('Application deadline',x.applicationDeadline);add('Programme starts',x.startDate);add('Programme ends',x.endDate)}else{add('Applications open',x.applicationOpens);add('Application deadline',x.applicationDeadline);add('Entry / cycle',x.entryCycle)}if(x.additionalDates)add('Other important dates',x.additionalDates);return items}
function s3DecisionFields(x){if(x.kind==='programmes')return[['Who can apply',x.schoolYears],['TY eligible',x.tyEligible],['Opportunity type',x.opportunityType],['Location',x.location||x.county||x.scope],['Delivery',x.mode],['Duration',x.duration],['Access',x.accessRestrictions||x.accessType],['Application route',x.entry||x.applicationMethod],['Cost',x.cost],['Selectivity',x.selectivity||x.places]];if(x.kind==='scholarships')return[['Applicant stage',x.applicantStage||x.schoolYears],['Study country',x.studyCountry],['Institution',x.studyInstitution],['Funding type',x.fundingType],['Award basis',x.awardBasis],['Financial need',x.financialNeed],['Application route',x.entry],['Award value',x.awardValue],['Coverage',x.coverage],['Subject / course',x.subject]];return[['Who can enter',x.schoolYears],['TY eligible',x.tyEligible],['Competition type',x.competitionType],['Level',x.competitionLevel],['Format',pick(x.raw,indexed(x.raw),'Individual / Team / Both','Individual / Team')],['Entry route',x.entry],['Student direct entry',x.studentDirect],['School registration',x.schoolRegister],['Teacher/coordinator',x.teacherRequired],['Cost',x.cost]]}
function s3Sources(x){return[
 {label:'Official provider page',url:x.url,note:'Primary public source'},
 {label:'Current cycle / intake page',url:x.currentPage,note:x.dateStatus||'Current-cycle evidence'},
 {label:'Eligibility evidence',url:x.eligibilitySource,note:x.eligibilityChecked?'Eligibility checked '+x.eligibilityChecked:'Eligibility source'},
 {label:'Cost / award evidence',url:x.costSource,note:x.costChecked?'Cost checked '+x.costChecked:'Cost source'},
 {label:'Monitoring source',url:x.monitoringSource,note:x.lastVerified?'Last verified '+x.lastVerified:'Monitoring evidence'}
].filter(s=>text(s.url))}
function s3SourceHtml(x){const list=s3Sources(x);if(!list.length)return'<p>No separate source links are published for this record. Use the official page above for final confirmation.</p>';return'<div class="provenance-list">'+list.map(s=>'<div class="provenance-item"><div><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.label)+' ↗</a><small>'+esc(s.note)+'</small></div><span class="source-state">Source</span></div>').join('')+'</div>'}
function s3RelatedScore(a,b){let score=0;if(a.kind===b.kind)score+=2;if(norm(a.subject)&&norm(a.subject)===norm(b.subject))score+=7;if(a.subcategory&&b.subcategory&&norm(a.subcategory)===norm(b.subcategory))score+=4;if(a.provider&&b.provider&&norm(a.provider)===norm(b.provider))score+=2;if(a.geography&&b.geography&&norm(a.geography)===norm(b.geography))score+=2;const ay=norm(a.schoolYears),by=norm(b.schoolYears);if(ay&&by&&ay.split(/[,/]/).some(y=>y.trim()&&by.includes(y.trim())))score+=3;if(a.opportunityType&&b.opportunityType&&norm(a.opportunityType)===norm(b.opportunityType))score+=2;return score}
function s3RelatedFallback(x,limit=5){return allData().filter(y=>y.id&&y.id!==x.id).map(y=>({y,score:s3RelatedScore(x,y)})).filter(z=>z.score>0).sort((a,b)=>b.score-a.score||a.y.name.localeCompare(b.y.name)).slice(0,limit).map(z=>z.y)}
async function s3GetRelated(x){const key=x.kind+'|'+x.id;if(relatedCache.has(key))return relatedCache.get(key);let out=[];if(C.API_BASE_URL){try{const r=await jsonp(C.API_BASE_URL+'?api=related&kind='+encodeURIComponent(x.kind)+'&id='+encodeURIComponent(x.id)+'&limit=5');const arr=Array.isArray(r)?r:(r?.records||r?.items||[]);out=arr.map(y=>mapRecord(y,y.kind||x.kind)).filter(y=>y.id&&y.id!==x.id)}catch(e){console.warn('Related API unavailable; using local similarity fallback',e)}}if(!out.length)out=s3RelatedFallback(x,5);relatedCache.set(key,out);return out}
function s3RelatedHtml(items){if(!items.length)return'<p>No strong related matches are available yet.</p>';return'<div class="related-grid">'+items.map(y=>'<article class="related-card"><span class="type">'+esc(typeLabel(y.kind))+(y.subject?' · '+esc(y.subject):'')+'</span><h4>'+esc(y.name)+'</h4><p>'+esc(y.provider||'')+'</p><button data-detail="'+esc(y.id)+'">View opportunity</button></article>').join('')+'</div>'}
function s3FeedbackForm(x){return'<div class="feedback-box"><button class="feedback-toggle" data-feedback-toggle="'+esc(x.id)+'">Report a problem or suggest an update</button><form class="feedback-form" id="feedbackForm" data-feedback-id="'+esc(x.id)+'"><label for="feedbackType">What needs attention?</label><select id="feedbackType" required><option value="">Choose an issue</option><option>Broken link</option><option>Changed deadline or date</option><option>Incorrect eligibility</option><option>Discontinued opportunity</option><option>Missing information</option><option>Suggestion</option></select><label for="feedbackMessage">What should we check?</label><textarea id="feedbackMessage" maxlength="1500" required placeholder="Briefly explain what appears wrong or what should be updated."></textarea><p class="anonymous-note">Anonymous report — no name or email is requested.</p><div class="feedback-actions"><button type="submit">Send report</button><span id="feedbackStatus" class="feedback-status"></span></div></form></div>'}
function s3DetailBody(x){const fresh=s3Freshness(x),timeline=s3Timeline(x),fields=s3DecisionFields(x).filter(([,v])=>text(v)),direct=s3DirectUrl(x);return'<div class="detail-hero"><div class="detail-hero-top"><div><div class="detail-statuses"><span class="badge">'+esc(displayStatus(x))+'</span>'+(x.subject?'<span class="badge sub">'+esc(x.subject)+'</span>':'')+(x.dateStatus?'<span class="badge expected">'+esc(x.dateStatus)+'</span>':'')+'</div><div class="freshness-row" style="margin-top:9px"><span class="freshness '+fresh.cls+'">'+esc(fresh.label)+'</span>'+(x.verificationConfidence?'<span class="freshness">Confidence: '+esc(x.verificationConfidence)+'</span>':'')+'</div></div></div><div class="detail-actions-row">'+(x.url?'<a class="primary-link" href="'+esc(x.url)+'" target="_blank" rel="noopener">Official page ↗</a>':'')+'<button data-direct-copy="'+esc(x.id)+'">Copy direct link</button><button data-direct-share="'+esc(x.id)+'">Share opportunity</button><button data-save="'+esc(x.id)+'">'+(saved.has(x.id)?'♥ Saved':'♡ Save')+'</button></div></div><div class="detail-columns"><div><section class="detail-panel"><h3>About this opportunity</h3><p>'+esc(x.description||'No extended description is published in the public record yet.')+'</p></section>'+(x.eligibility?'<section class="detail-panel"><h3>Eligibility & restrictions</h3><p>'+esc(x.eligibility)+'</p></section>':'')+'<section class="detail-panel"><h3>Key decision details</h3><div class="detail-grid">'+fields.map(([l,v])=>fact(l,v)).join('')+'</div></section>'+(x.costNotes?'<section class="detail-panel"><h3>Cost / award notes</h3><p>'+esc(x.costNotes)+'</p></section>':'')+'<section class="detail-panel"><h3>Important dates</h3>'+(timeline.length?'<div class="timeline-list">'+timeline.map(([l,v])=>'<div class="timeline-item"><b>'+esc(l)+'</b><span>'+esc(v)+'</span></div>').join('')+'</div>':'<p>No exact dated milestone is currently published for this record.</p>')+'</section></div><aside><section class="detail-panel"><h3>Verification & freshness</h3><div class="detail-grid">'+fact('Last verified',x.lastVerified)+fact('Eligibility checked',x.eligibilityChecked)+fact('Cost checked',x.costChecked)+fact('Confidence',x.verificationConfidence)+fact('Date status',x.dateStatus)+fact('Record ID',x.id)+'</div></section><section class="detail-panel"><h3>Source provenance</h3>'+s3SourceHtml(x)+'</section></aside></div><section class="detail-panel" style="margin-top:14px"><h3>Related opportunities</h3><div id="relatedHost" class="related-loading">Finding the closest related opportunities…</div></section>'+s3FeedbackForm(x)}
const s3BaseDetails=details;
details=async function(id){const x=find(id);if(!x)return;$('dtype').textContent=typeLabel(x.kind)+(x.id?' · '+x.id:'');$('dtitle').textContent=x.name;$('dprovider').textContent=x.provider||'';$('dbody').innerHTML=s3DetailBody(x);if(!$('dialog').open)$('dialog').showModal();history.replaceState(null,'',urlFor({id:x.id}));const related=await s3GetRelated(x);if($('dialog').open&&find(id)?.id===x.id){const host=$('relatedHost');if(host)host.outerHTML='<div id="relatedHost">'+s3RelatedHtml(related)+'</div>'}}
async function s3SubmitFeedback(form){const id=form.dataset.feedbackId,x=find(id),status=$('feedbackStatus'),type=$('feedbackType').value,message=$('feedbackMessage').value.trim();if(!x||!type||!message)return;if(!C.API_BASE_URL){status.textContent='Feedback endpoint is unavailable.';return}status.textContent='Sending…';const payload={id:x.id,opportunityId:x.id,kind:x.kind,opportunityType:typeLabel(x.kind),opportunityName:x.name,title:x.name,issueType:type,category:type,message,details:message,sourceUrl:x.url||'',pageUrl:s3DirectUrl(x),submittedAt:new Date().toISOString()};try{await fetch(C.API_BASE_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({action:'feedback',payload})});status.textContent='Report sent for review.';form.reset()}catch(e){console.warn(e);status.textContent='Could not send this report. Please try again.'}}
document.addEventListener('click',async e=>{const toggle=e.target.closest('[data-feedback-toggle]');if(toggle){$('feedbackForm')?.classList.toggle('on')}const copy=e.target.closest('[data-direct-copy]');if(copy){const x=find(copy.dataset.directCopy);if(x)await s3Copy(s3DirectUrl(x),copy,'Link copied!')}const share=e.target.closest('[data-direct-share]');if(share){const x=find(share.dataset.directShare);if(x){const u=s3DirectUrl(x);if(navigator.share){try{await navigator.share({title:x.name,text:x.provider||'Irish Academic Opportunities Finder',url:u})}catch(_){}}else await s3Copy(u,share,'Link copied!')}}});
document.addEventListener('submit',e=>{const form=e.target.closest('#feedbackForm');if(form){e.preventDefault();s3SubmitFeedback(form)}});
