/* Stage 4 production hardening: mobile nav, accessibility, health notices, print and PWA update behavior. */
(function(){
  const byId=id=>document.getElementById(id);
  function ensureStructure(){
    const main=document.querySelector('main');if(main&&!main.id)main.id='mainContent';
    if(!document.querySelector('.skip-link')){const a=document.createElement('a');a.className='skip-link';a.href='#mainContent';a.textContent='Skip to main content';document.body.prepend(a)}
    const head=document.querySelector('.head'),nav=document.querySelector('.nav');if(nav&&!nav.id)nav.id='mainNav';
    if(head&&nav&&!byId('mobileMenu')){const b=document.createElement('button');b.id='mobileMenu';b.className='mobile-menu';b.type='button';b.setAttribute('aria-controls','mainNav');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation menu');b.innerHTML='<span class="mobile-menu-bars" aria-hidden="true"><i></i><i></i><i></i></span>';head.insertBefore(b,nav)}
    if(!byId('siteNotice')){const n=document.createElement('div');n.id='siteNotice';n.className='site-notice';n.setAttribute('role','status');n.setAttribute('aria-live','polite');n.innerHTML='<div class="site-notice-inner"><span id="siteNoticeText"></span><button id="siteNoticeAction" class="hide" type="button"></button></div>';document.querySelector('header')?.after(n)}
    byId('status')?.setAttribute('aria-live','polite');byId('resultCount')?.setAttribute('aria-live','polite');byId('calendarCount')?.setAttribute('aria-live','polite');
    byId('results')?.setAttribute('aria-busy','false');byId('calendarResults')?.setAttribute('aria-busy','false');
    const actions=document.querySelector('.toolbar-actions');if(actions&&!byId('printShortlist')){const b=document.createElement('button');b.id='printShortlist';b.className='saved print-btn';b.type='button';b.textContent='Print shortlist';actions.appendChild(b)}
    if(!byId('printArea')){const p=document.createElement('section');p.id='printArea';p.className='print-area';p.setAttribute('aria-hidden','true');document.body.appendChild(p)}
  }
  function showNotice(message,kind='info',actionLabel='',action=null){const n=byId('siteNotice'),t=byId('siteNoticeText'),b=byId('siteNoticeAction');if(!n||!t||!b)return;t.innerHTML=message;n.className='site-notice on '+kind;if(actionLabel&&action){b.textContent=actionLabel;b.classList.remove('hide');b.onclick=action}else{b.classList.add('hide');b.onclick=null}}
  function hideNotice(){const n=byId('siteNotice');if(n)n.className='site-notice'}
  function dataHealth(){if(!navigator.onLine){showNotice('<span class="offline-dot"></span>You are offline. Saved pages and previously cached site assets may still be available.','error');return}const s=(byId('status')?.textContent||'').trim();if(/frontend preview/i.test(s)){showNotice('Live opportunity data could not be reached, so a small built-in preview is being shown. Try refreshing when your connection is stable.','error','Retry',()=>location.reload());return}if(/live data/i.test(s)){try{if(typeof allData==='function'&&allData().length===0){showNotice('The live service responded but returned no opportunity records. Please retry before relying on this view.','error','Retry',()=>location.reload());return}}catch(_){}hideNotice()}}
  function syncBusy(){const busy=document.body.classList.contains('loading')?'true':'false';byId('results')?.setAttribute('aria-busy',busy);byId('calendarResults')?.setAttribute('aria-busy',busy)}
  function syncNav(){let current='home';try{if(typeof tab!=='undefined')current=tab}catch(_){}document.querySelectorAll('[data-tab]').forEach(el=>{if(el.dataset.tab===current)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')})}
  function closeMenu(){const nav=byId('mainNav'),b=byId('mobileMenu');nav?.classList.remove('open');if(b){b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation menu')}}
  function toggleMenu(){const nav=byId('mainNav'),b=byId('mobileMenu');if(!nav||!b)return;const open=!nav.classList.contains('open');nav.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu')}
  function printValue(v){return typeof esc==='function'?esc(v||''):String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function buildPrint(){let rows=[];try{rows=Array.isArray(lastFiltered)?lastFiltered:[]}catch(_){}try{if(typeof tab!=='undefined'&&tab==='saved'&&typeof allData==='function')rows=allData().filter(x=>saved.has(x.id))}catch(_){}const total=rows.length,limit=Math.min(total,100),shown=rows.slice(0,limit),title=(byId('title')?.textContent||'Opportunity shortlist'),filters=typeof activeFilterPairs==='function'?activeFilterPairs():[];const meta=filters.length?filters.map(([a,b])=>a+': '+b).join(' · '):'No filters';const items=shown.map(x=>{let date='';try{const nd=nextDate(x);date=nd?nd.label+': '+nd.value:''}catch(_){}const geo=x.studyCountry||x.location||x.county||x.competitionLevel||x.scope||'';const cost=x.kind==='scholarships'?(x.awardValue||x.coverage||''):(x.cost||'');return '<article class="print-item"><h2>'+printValue(x.name)+'</h2><p><strong>'+printValue(x.provider||typeLabel(x.kind))+'</strong></p><div class="print-meta"><span><b>Subject:</b> '+printValue(x.subject||'—')+'</span><span><b>Eligible:</b> '+printValue(x.schoolYears||x.applicantStage||'—')+'</span><span><b>Location:</b> '+printValue(geo||'—')+'</span><span><b>Status:</b> '+printValue(displayStatus(x))+'</span><span><b>'+(x.kind==='scholarships'?'Award':'Cost')+':</b> '+printValue(cost||'—')+'</span><span><b>Next date:</b> '+printValue(date||'—')+'</span></div>'+(x.url?'<p class="print-url">'+printValue(x.url)+'</p>':'')+'</article>'}).join('');const note=total>100?'Showing the first 100 of '+total+' matching opportunities. Narrow the finder filters for a shorter printable list.':total+' opportunit'+(total===1?'y':'ies')+' in this shortlist.';byId('printArea').innerHTML='<div class="print-head"><h1>'+printValue(title)+'</h1><p>Irish Academic Opportunities Finder</p><p>'+printValue(meta)+'</p><p>'+printValue(note)+'</p></div><div class="print-list">'+(items||'<p>No opportunities are currently in this shortlist.</p>')+'</div><div class="print-foot">Generated from the live finder. Dates, eligibility, costs and award values can change; confirm final details on each official provider page before applying.</div>'}
  function printShortlist(){buildPrint();requestAnimationFrame(()=>window.print())}
  ensureStructure();syncNav();syncBusy();
  byId('mobileMenu')?.addEventListener('click',toggleMenu);byId('printShortlist')?.addEventListener('click',printShortlist);
  document.addEventListener('click',e=>{if(e.target.closest('[data-tab]')){setTimeout(()=>{syncNav();closeMenu()},0)}else if(window.innerWidth<=900&&!e.target.closest('header'))closeMenu()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'')){e.preventDefault();const target=byId('q')&&typeof tab!=='undefined'&&tab!=='home'?byId('q'):byId('heroSearch');target?.focus()}});
  window.addEventListener('resize',()=>{if(window.innerWidth>900)closeMenu()});window.addEventListener('online',dataHealth);window.addEventListener('offline',dataHealth);
  const status=byId('status');if(status)new MutationObserver(()=>setTimeout(dataHealth,0)).observe(status,{childList:true,characterData:true,subtree:true});new MutationObserver(syncBusy).observe(document.body,{attributes:true,attributeFilter:['class']});
  window.addEventListener('error',e=>{const tag=e.target?.tagName;if(tag==='SCRIPT'||tag==='LINK')showNotice('A required site file did not load correctly. Refresh the page to retry.','error','Refresh',()=>location.reload())},true);
  if('serviceWorker'in navigator&&navigator.serviceWorker.controller){let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()})}
  setTimeout(dataHealth,1800);
})();
