/**
 * Stage9Autonomous.gs — controlled autonomous maintenance for Irish Academic Opportunities.
 * Stage 7 remains the evidence layer. Stage 9 auto-applies only high-confidence,
 * directly evidenced official-source changes and rolls back if release gates fail.
 */

const STAGE9_CONFIG = Object.freeze({
  VERSION: '9.0.0',
  SPREADSHEET_ID: '1JH84XrYYxOlZgM8zqt9bn4Ndo-QwnpouDbgvMAoVevs',
  TIMEZONE: 'Europe/Dublin',
  USER_AGENT: 'Mozilla/5.0 (compatible; IrishAcademicOpportunitiesAutonomy/9.0; +https://liamsomers08.github.io/Irish-Academic-Opportunities/)',
  MIN_READABLE_CHARS: 180,
  DEFAULT_REVIEW_LIMIT: 24,
  DEFAULT_WRITE_LIMIT: 12,
  DEFAULT_RETRY_DEFERRED_DAYS: 7,
  AUTO_CONFIDENCE_THRESHOLD: 90,
  MAX_SOURCE_CHARS: 80000,
  DAILY_HOUR: 8,
  DAILY_MINUTE: 15,
  SHEETS: Object.freeze({policy:'Automation Policy',changeLog:'Autonomous Change Log',review:'Operations Review Queue',runLog:'Operations Run Log',dashboard:'Operations Dashboard',regression:'WebApp Regression Tests',admin:'WebApp Admin Dashboard'}),
  KINDS: Object.freeze({
    competitions: Object.freeze({key:'competitions',master:'Competitions',idHeader:'Competition ID',nameHeader:'Competition Name',sourceHeaders:['Current Year Page','Official Website'],statusHeader:'Status',openValue:'Available',closedValue:'Closed',dateRules:Object.freeze([
      Object.freeze({field:'Registration Opens',labels:['registration opens','registration opens on','registration will open']}),
      Object.freeze({field:'Registration Deadline',labels:['registration deadline','registration closes','registration closes on']}),
      Object.freeze({field:'Submission Deadline',labels:['submission deadline','submissions close','entry deadline','entries close','entries close on']})
    ])}),
    programmes: Object.freeze({key:'programmes',master:'Programmes',idHeader:'Programme ID',nameHeader:'Programme Name',sourceHeaders:['Monitoring Source','Current Intake Page','Official Website'],statusHeader:'Application Status',openValue:'Open',closedValue:'Closed',dateRules:Object.freeze([
      Object.freeze({field:'Application Opens',labels:['applications open','applications open on','application opens','application opens on']}),
      Object.freeze({field:'Application Deadline',labels:['application deadline','applications close','applications close on','closing date','apply by']}),
      Object.freeze({field:'Programme Start Date',labels:['programme starts','programme starts on','program starts','start date']}),
      Object.freeze({field:'Programme End Date',labels:['programme ends','programme ends on','program ends','end date']})
    ])}),
    scholarships: Object.freeze({key:'scholarships',master:'Scholarships',idHeader:'Scholarship ID',nameHeader:'Scholarship Name',sourceHeaders:['Official Link'],statusHeader:'Current Status',openValue:'Open',closedValue:'Closed',dateRules:Object.freeze([
      Object.freeze({field:'Application Deadline',labels:['application deadline','applications close','applications close on','closing date','apply by']})
    ])})
  })
});

function stage9Install(){
  const ss=stage9Spreadsheet_();stage9EnsureSheets_(ss);const trigger=stage9EnsureTrigger_();PropertiesService.getScriptProperties().setProperty('stage9_bootstrap_version',STAGE9_CONFIG.VERSION);
  stage9SetDashboardStatus_('Installed','Active','Stage 9 autonomous maintenance is enabled; '+trigger+'.');
  stage9AppendRunLog_({job:'stage9-install',checked:0,changes:0,errors:0,reviewItems:0,notes:'Stage 9 '+STAGE9_CONFIG.VERSION+' installed. High-confidence auto-apply is enabled with regression rollback.'});
  return {ok:true,version:STAGE9_CONFIG.VERSION,trigger:trigger,policy:stage9GetPolicy_(ss)};
}
function stage9RunNow(){return stage9RunDaily();}
function stage9RunDaily(){
  const started=Date.now(),lock=LockService.getScriptLock();if(!lock.tryLock(5000))return {ok:false,skipped:true,reason:'Another Stage 9 run is active.'};
  try{
    const ss=stage9Spreadsheet_();stage9EnsureSheets_(ss);const policy=stage9GetPolicy_(ss);
    if(!policy.enabled){stage9AppendRunLog_({job:'autonomous-maintenance',checked:0,changes:0,errors:0,reviewItems:0,notes:'Skipped: Automation Policy is disabled.'});return {ok:true,skipped:true,reason:'disabled'};}
    const reviewSheet=ss.getSheetByName(STAGE9_CONFIG.SHEETS.review);
    if(!reviewSheet||reviewSheet.getLastRow()<2){stage9AppendRunLog_({job:'autonomous-maintenance',checked:0,changes:0,errors:0,reviewItems:0,notes:'No operations review items available.'});return {ok:true,checked:0,applied:0,deferred:0};}
    const reviews=stage9SelectReviews_(reviewSheet,policy.reviewLimit,policy.retryDeferredDays);
    if(!reviews.length){stage9AppendRunLog_({job:'autonomous-maintenance',checked:0,changes:0,errors:0,reviewItems:0,notes:'No eligible New/Deferred review items for Stage 9.'});stage9SetDashboardStatus_('Installed','Active','Last Stage 9 run: '+stage9FormatDateTime_(new Date())+' — no eligible review work.');return {ok:true,checked:0,applied:0,deferred:0};}
    const runId=Utilities.getUuid(),plans=[],outcomes=[];let fetchErrors=0;
    reviews.forEach(function(review){const result=stage9PlanReview_(ss,review,policy);outcomes.push(result);if(result.error)fetchErrors++;(result.candidates||[]).forEach(function(c){plans.push(c);});});
    const deduped=stage9DedupeCandidates_(plans).sort(function(a,b){return b.confidence-a.confidence;}).slice(0,policy.writeLimit);
    const applied=policy.autoApply?stage9ApplyWithRegression_(ss,deduped,runId,policy):{ok:true,applied:[],rolledBack:false,gate:{pass:true,detail:'Dry-run / auto-apply disabled'}};
    const appliedReviewIds={};(applied.applied||[]).forEach(function(change){(change.reviewIds||[]).forEach(function(id){appliedReviewIds[id]=true;});});
    let deferred=0,updated=0,noChange=0;
    outcomes.forEach(function(result){const review=result.review;if(appliedReviewIds[review.reviewId]&&!applied.rolledBack){stage9SetReviewStatus_(reviewSheet,review.row,'Data updated','Stage 9 auto-applied high-confidence official-source change(s); regression gate passed. Run '+runId+'.');updated++;}else if(result.explicitMatches&&!result.candidates.length&&policy.resolveExplicitNoChange){stage9SetReviewStatus_(reviewSheet,review.row,'Reviewed - no data change','Stage 9 found explicit managed fields on the official source and they match the master. Run '+runId+'.');noChange++;}else if(result.sourceInaccessible){stage9SetReviewStatus_(reviewSheet,review.row,'Source inaccessible','Stage 9 could not safely read the source: '+(result.reason||'unknown source error')+'.');deferred++;}else{const reason=applied.rolledBack?'Regression gate failed; all Stage 9 writes were rolled back.':(result.reason||'No green-rule change could be proven from one unambiguous official-source value.');stage9SetReviewStatus_(reviewSheet,review.row,'Deferred','Stage 9: '+reason+' Run '+runId+'.');deferred++;}});
    const notes='Stage 9 checked '+reviews.length+' review items; '+(applied.applied||[]).length+' field writes '+(applied.rolledBack?'rolled back':'committed')+'; '+updated+' reviews updated; '+deferred+' deferred; '+noChange+' no-change; '+fetchErrors+' source errors. Gate: '+(applied.gate&&applied.gate.detail||'n/a')+'.';
    stage9AppendRunLog_({job:'autonomous-maintenance',checked:reviews.length,changes:applied.rolledBack?0:(applied.applied||[]).length,errors:fetchErrors+(applied.rolledBack?1:0),reviewItems:deferred,duration:Date.now()-started,notes:notes});stage9SetDashboardStatus_('Installed',applied.rolledBack?'Guarded':'Active','Last Stage 9 run: '+stage9FormatDateTime_(new Date())+' — '+notes);
    return {ok:!applied.rolledBack,runId:runId,checked:reviews.length,applied:applied.rolledBack?0:(applied.applied||[]).length,deferred:deferred,noChange:noChange,gate:applied.gate};
  }finally{lock.releaseLock();}
}

function stage9PlanReview_(ss,review,policy){
  const result={review:review,candidates:[],explicitMatches:false,sourceInaccessible:false,reason:'',error:false},def=STAGE9_CONFIG.KINDS[review.kind];
  if(!def){result.reason='Unsupported review kind';return result;}if(!stage9ReviewIssueEligible_(review.issueType)){result.reason='Issue type is intentionally not auto-written';return result;}
  const record=stage9FindMasterRecord_(ss,def,review.opportunityId);if(!record){result.reason='Master record not found';return result;}const sourceUrl=review.sourceUrl||stage9FirstHeaderValue_(record.rowValues,record.headers,def.sourceHeaders);if(!sourceUrl){result.reason='No official/current source stored';return result;}
  const fetched=stage9FetchSource_(sourceUrl);if(!fetched.ok){result.sourceInaccessible=true;result.error=true;result.reason=fetched.reason;return result;}const contextInfo=stage9OpportunityContext_(fetched.text,record.name,sourceUrl);if(contextInfo.relevance<0.30){result.reason='Official source was readable but did not contain enough opportunity-specific context';return result;}
  const statusCandidate=policy.autoStatuses?stage9StatusCandidate_(def,record,contextInfo,sourceUrl,review):null;if(statusCandidate){if(stage9Equivalent_(statusCandidate.oldValue,statusCandidate.newValue))result.explicitMatches=true;else result.candidates.push(statusCandidate);}
  if(policy.autoDates)def.dateRules.forEach(function(rule){const candidate=stage9DateCandidate_(def,record,rule,contextInfo,sourceUrl,review);if(!candidate)return;if(stage9EquivalentDate_(candidate.oldValue,candidate.newValue))result.explicitMatches=true;else result.candidates.push(candidate);});
  if(!result.candidates.length&&!result.explicitMatches)result.reason='No unambiguous green-rule status/date value was found on the official source';return result;
}
function stage9StatusCandidate_(def,record,contextInfo,sourceUrl,review){
  const context=contextInfo.context.toLowerCase(),closedSignals=['applications are now closed','applications are closed','applications have now closed','applications have closed','entries are now closed','entries are closed','registration is now closed','registration is closed','submissions are now closed','submissions are closed','no longer accepting applications','deadline has passed'],openSignals=['applications are now open','applications are open','applications are currently open','now accepting applications','entries are now open','entries are open','registration is now open','registration is open'],closed=stage9FirstSignal_(context,closedSignals),open=stage9FirstSignal_(context,openSignals);if((!closed&&!open)||(closed&&open))return null;
  const col=stage9FindHeader_(record.headers,[def.statusHeader]);if(col<0||record.formulas[col])return null;const newValue=closed?def.closedValue:def.openValue;let confidence=contextInfo.baseScore+50+15;confidence=Math.min(100,confidence);if(confidence<STAGE9_CONFIG.AUTO_CONFIDENCE_THRESHOLD)return null;
  return {key:def.master+'!'+record.rowNumber+'!'+(col+1),kind:def.key,sheet:def.master,row:record.rowNumber,col:col+1,opportunityId:record.id,opportunityName:record.name,field:def.statusHeader,oldValue:record.rowValues[col],newValue:newValue,confidence:confidence,sourceUrl:sourceUrl,evidence:'Explicit status signal: “'+(closed||open)+'”',reviewIds:[review.reviewId]};
}
function stage9DateCandidate_(def,record,rule,contextInfo,sourceUrl,review){const extracted=stage9ExtractUniqueDate_(contextInfo.context,rule.labels);if(!extracted)return null;const col=stage9FindHeader_(record.headers,[rule.field]);if(col<0||record.formulas[col])return null;let confidence=contextInfo.baseScore+40+15+(stage9PlausibleCycleDate_(extracted.date)?10:0);confidence=Math.min(100,confidence);if(confidence<STAGE9_CONFIG.AUTO_CONFIDENCE_THRESHOLD)return null;return {key:def.master+'!'+record.rowNumber+'!'+(col+1),kind:def.key,sheet:def.master,row:record.rowNumber,col:col+1,opportunityId:record.id,opportunityName:record.name,field:rule.field,oldValue:record.rowValues[col],newValue:extracted.date,confidence:confidence,sourceUrl:sourceUrl,evidence:'Exact labelled date: '+extracted.label+' → '+stage9FormatDate_(extracted.date)+'; source context: '+extracted.snippet,reviewIds:[review.reviewId]};}

function stage9ApplyWithRegression_(ss,candidates,runId,policy){
  if(!candidates.length)return {ok:true,applied:[],rolledBack:false,gate:{pass:true,detail:'No field writes required'}};const snapshots=[],applied=[];
  try{candidates.forEach(function(candidate){const sheet=ss.getSheetByName(candidate.sheet);if(!sheet)throw new Error('Missing master sheet '+candidate.sheet);const cell=sheet.getRange(candidate.row,candidate.col),oldFormula=cell.getFormula();if(oldFormula)return;snapshots.push({sheet:candidate.sheet,row:candidate.row,col:candidate.col,value:cell.getValue(),formula:oldFormula,numberFormat:cell.getNumberFormat()});cell.setValue(candidate.newValue);applied.push(candidate);});SpreadsheetApp.flush();const gate=policy.regressionGate?stage9RegressionGate_(ss):{pass:true,detail:'Regression gate disabled by policy'};if(!gate.pass){stage9Rollback_(ss,snapshots);stage9WriteChangeLog_(ss,applied,runId,'ROLLED BACK',gate.detail);return {ok:false,applied:applied,rolledBack:true,gate:gate};}stage9WriteChangeLog_(ss,applied,runId,'APPLIED',gate.detail);return {ok:true,applied:applied,rolledBack:false,gate:gate};}
  catch(err){stage9Rollback_(ss,snapshots);const gate={pass:false,detail:'Runtime error: '+stage9ShortError_(err)};stage9WriteChangeLog_(ss,applied,runId,'ROLLED BACK',gate.detail);return {ok:false,applied:applied,rolledBack:true,gate:gate};}
}
function stage9Rollback_(ss,snapshots){snapshots.slice().reverse().forEach(function(s){const cell=ss.getSheetByName(s.sheet).getRange(s.row,s.col);if(s.formula)cell.setFormula(s.formula);else cell.setValue(s.value);if(s.numberFormat)cell.setNumberFormat(s.numberFormat);});SpreadsheetApp.flush();}
function stage9RegressionGate_(ss){
  SpreadsheetApp.flush();const failures=[],regression=ss.getSheetByName(STAGE9_CONFIG.SHEETS.regression);if(!regression||regression.getLastRow()<2)failures.push('Regression test sheet missing');else{const rows=regression.getRange(2,1,regression.getLastRow()-1,Math.min(3,regression.getLastColumn())).getDisplayValues();rows.forEach(function(r){if(String(r[0]||'').trim()&&String(r[1]||'').trim().toUpperCase()!=='PASS')failures.push(String(r[0])+'='+String(r[1]||'blank'));});}
  const admin=ss.getSheetByName(STAGE9_CONFIG.SHEETS.admin);if(!admin)failures.push('Admin dashboard missing');else{const values=admin.getRange(1,1,Math.min(admin.getLastRow(),80),Math.min(admin.getLastColumn(),3)).getDisplayValues(),metrics={};values.forEach(function(r){if(r[0])metrics[stage9Canon_(r[0])]=String(r[1]||'');});[['dataqualityissues','Data quality issues'],['regressionfailures','Regression failures'],['regressionwarnings','Regression warnings'],['expectedresearchedrecordsstillmissing','Expected researched records still missing']].forEach(function(pair){if(metrics[pair[0]]!==undefined&&Number(metrics[pair[0]]||0)!==0)failures.push(pair[1]+'='+metrics[pair[0]]);});}
  return {pass:failures.length===0,detail:failures.length?'FAIL: '+failures.join('; '):'PASS: regression and data-quality gates clear'};
}

function stage9SelectReviews_(sheet,limit,retryDeferredDays){const width=Math.min(12,sheet.getLastColumn()),values=sheet.getRange(1,1,sheet.getLastRow(),width).getValues(),headers=stage9HeaderMap_(values[0]),c={id:stage9FindHeader_(headers,['Review ID']),detected:stage9FindHeader_(headers,['Detected At']),kind:stage9FindHeader_(headers,['Kind']),oppId:stage9FindHeader_(headers,['Opportunity ID']),name:stage9FindHeader_(headers,['Opportunity Name']),issue:stage9FindHeader_(headers,['Issue Type']),source:stage9FindHeader_(headers,['Source URL']),status:stage9FindHeader_(headers,['Review Status']),lastSeen:stage9FindHeader_(headers,['Last Seen'])},now=Date.now(),retryMs=retryDeferredDays*86400000,out=[];values.slice(1).forEach(function(row,i){const status=c.status>=0?String(row[c.status]||'').trim():'New',last=stage9DateMs_(c.lastSeen>=0?row[c.lastSeen]:'');if(!(/^new$/i.test(status)||(/^deferred$/i.test(status)&&(!last||now-last>=retryMs))))return;const issue=c.issue>=0?String(row[c.issue]||''):'';if(!stage9ReviewIssueEligible_(issue))return;out.push({row:i+2,reviewId:c.id>=0?String(row[c.id]||''):Utilities.getUuid(),detectedAt:c.detected>=0?row[c.detected]:'',kind:c.kind>=0?String(row[c.kind]||'').toLowerCase():'',opportunityId:c.oppId>=0?String(row[c.oppId]||''):'',opportunityName:c.name>=0?String(row[c.name]||''):'',issueType:issue,sourceUrl:c.source>=0?String(row[c.source]||''):''});});out.sort(function(a,b){return stage9DateMs_(a.detectedAt)-stage9DateMs_(b.detectedAt);});return out.slice(0,limit);}
function stage9ReviewIssueEligible_(issue){const s=String(issue||'').toLowerCase();if(/source content changed|page content changed|open status after stored deadline|master status needs review/.test(s))return true;if(/^feedback:/.test(s)&&/deadline|date|discontinued|closed|open/.test(s))return true;return false;}
function stage9FindMasterRecord_(ss,def,id){const sheet=ss.getSheetByName(def.master);if(!sheet||sheet.getLastRow()<2||!id)return null;const range=sheet.getDataRange(),values=range.getValues(),formulas=range.getFormulas(),headers=stage9HeaderMap_(values[0]),idCol=stage9FindHeader_(headers,[def.idHeader]),nameCol=stage9FindHeader_(headers,[def.nameHeader]);if(idCol<0)return null;for(let i=1;i<values.length;i++)if(String(values[i][idCol]||'').trim()===String(id).trim())return {sheet:sheet,headers:headers,rowValues:values[i],formulas:formulas[i],rowNumber:i+1,id:String(values[i][idCol]||''),name:nameCol>=0?String(values[i][nameCol]||''):String(id)};return null;}
function stage9FetchSource_(url){try{const response=UrlFetchApp.fetch(String(url),{method:'get',followRedirects:true,muteHttpExceptions:true,headers:{'User-Agent':STAGE9_CONFIG.USER_AGENT,'Accept':'text/html,application/xhtml+xml,*/*;q=0.6','Accept-Language':'en-IE,en;q=0.9'}}),code=Number(response.getResponseCode()||0);if(code<200||code>=400)return {ok:false,reason:'HTTP '+code};let body='';try{body=response.getContentText()||'';}catch(_){body='';}const text=stage9ReadableText_(body);if(text.length<STAGE9_CONFIG.MIN_READABLE_CHARS)return {ok:false,reason:'too little readable content ('+text.length+' chars)'};return {ok:true,code:code,text:text,html:body};}catch(err){return {ok:false,reason:stage9ShortError_(err)};}}
function stage9OpportunityContext_(text,name,url){const clean=String(text||''),tokens=stage9NameTokens_(name),lower=clean.toLowerCase();let hits=0,firstIndex=-1;tokens.forEach(function(token){const idx=lower.indexOf(token);if(idx>=0){hits++;if(firstIndex<0||idx<firstIndex)firstIndex=idx;}});const denom=Math.max(1,Math.min(tokens.length,6)),relevance=Math.min(1,hits/denom);let context=clean;if(firstIndex>=0)context=clean.slice(Math.max(0,firstIndex-1000),Math.min(clean.length,firstIndex+5000));let deep=false;try{const m=String(url||'').match(/^https?:\/\/[^/]+(\/[^?#]*)?/i),p=String(m&&m[1]||'').replace(/^\/+|\/+$/g,'');deep=p.length>=5&&p.split('/').filter(Boolean).length>=1;}catch(_){}let baseScore=deep?15:5;if(relevance>=0.75)baseScore+=35;else if(relevance>=0.5)baseScore+=25;else if(relevance>=0.3)baseScore+=15;return {context:context,relevance:relevance,baseScore:baseScore,deep:deep};}
function stage9NameTokens_(name){const stop={young:1,student:1,students:1,international:1,ireland:1,irish:1,competition:1,contest:1,award:1,awards:1,programme:1,program:1,scholarship:1,scholarships:1,challenge:1,the:1,and:1,for:1,year:1},seen={};return String(name||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(function(t){if(t.length<4||stop[t]||seen[t])return false;seen[t]=true;return true;}).slice(0,10);}
function stage9FirstSignal_(text,signals){for(let i=0;i<signals.length;i++)if(text.indexOf(signals[i])>=0)return signals[i];return '';}
function stage9ExtractUniqueDate_(text,labels){const lower=String(text||'').toLowerCase(),found={};labels.forEach(function(label){let pos=0;while((pos=lower.indexOf(label.toLowerCase(),pos))>=0){const snippet=String(text).slice(pos,Math.min(String(text).length,pos+240));stage9DatesInText_(snippet).forEach(function(item){if(!stage9PlausibleCycleDate_(item.date))return;const key=Utilities.formatDate(item.date,STAGE9_CONFIG.TIMEZONE,'yyyy-MM-dd');found[key]={date:item.date,label:label,snippet:snippet.slice(0,220)};});pos+=label.length;}});const keys=Object.keys(found);return keys.length===1?found[keys[0]]:null;}
function stage9DatesInText_(text){const out=[],seen={},months={jan:0,january:0,feb:1,february:1,mar:2,march:2,apr:3,april:3,may:4,jun:5,june:5,jul:6,july:6,aug:7,august:7,sep:8,sept:8,september:8,oct:9,october:9,nov:10,november:10,dec:11,december:11};function add(d,raw){if(!d||isNaN(d.getTime()))return;const k=d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate();if(!seen[k]){seen[k]=true;out.push({date:d,raw:raw});}}let m,re=/\b(\d{1,2})(?:st|nd|rd|th)?\s+(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s*,?\s*(20\d{2})\b/gi;while((m=re.exec(text))!==null)add(new Date(Number(m[3]),months[m[2].toLowerCase()],Number(m[1])),m[0]);re=/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s+(\d{1,2})(?:st|nd|rd|th)?\s*,?\s*(20\d{2})\b/gi;while((m=re.exec(text))!==null)add(new Date(Number(m[3]),months[m[1].toLowerCase()],Number(m[2])),m[0]);re=/\b(20\d{2})-(\d{2})-(\d{2})\b/g;while((m=re.exec(text))!==null)add(new Date(Number(m[1]),Number(m[2])-1,Number(m[3])),m[0]);return out;}
function stage9PlausibleCycleDate_(d){const y=d.getFullYear(),now=new Date().getFullYear();return y>=now-1&&y<=now+2;}
function stage9DedupeCandidates_(items){const map={};items.forEach(function(item){const current=map[item.key];if(!current){map[item.key]=item;return;}if(stage9EquivalentDate_(current.newValue,item.newValue)||stage9Equivalent_(current.newValue,item.newValue)){current.confidence=Math.max(current.confidence,item.confidence);current.reviewIds=(current.reviewIds||[]).concat(item.reviewIds||[]);current.evidence=current.evidence+' | '+item.evidence;}else if(item.confidence>current.confidence)map[item.key]=item;});return Object.keys(map).map(function(k){const x=map[k];x.reviewIds=Array.from(new Set(x.reviewIds||[]));return x;});}
function stage9WriteChangeLog_(ss,changes,runId,outcome,gate){const sheet=ss.getSheetByName(STAGE9_CONFIG.SHEETS.changeLog);if(!sheet)return;changes.forEach(function(c){sheet.appendRow([Utilities.getUuid(),new Date(),runId,c.kind,c.opportunityId,c.opportunityName,c.field,stage9DisplayValue_(c.oldValue),stage9DisplayValue_(c.newValue),c.confidence,c.sourceUrl,c.evidence,outcome,gate,(c.reviewIds||[]).join(',')]);});}
function stage9SetReviewStatus_(sheet,row,status,note){sheet.getRange(row,10,1,3).setValues([[status,note,new Date()]]);}

function stage9EnsureSheets_(ss){let policy=ss.getSheetByName(STAGE9_CONFIG.SHEETS.policy);if(!policy){policy=ss.insertSheet(STAGE9_CONFIG.SHEETS.policy,Math.min(9,ss.getNumSheets()),{rows:40,columns:4});stage9SeedPolicy_(policy);}let log=ss.getSheetByName(STAGE9_CONFIG.SHEETS.changeLog);if(!log){log=ss.insertSheet(STAGE9_CONFIG.SHEETS.changeLog,ss.getNumSheets(),{rows:3000,columns:15});log.getRange(1,1,1,15).setValues([['Change ID','Applied At','Run ID','Kind','Opportunity ID','Opportunity Name','Field','Old Value','New Value','Confidence','Source URL','Evidence','Outcome','Regression Gate','Review IDs']]);stage9StyleHeader_(log,15);log.setFrozenRows(1);log.hideSheet();}}
function stage9SeedPolicy_(sheet){const rows=[['STAGE 9 AUTOMATION POLICY','Value','Meaning','Safety'],['Version',STAGE9_CONFIG.VERSION,'Runtime policy version','Informational'],['Enabled','Yes','Master switch for Stage 9','Set No for immediate kill switch'],['Auto apply green changes','Yes','Commit high-confidence status/date changes','Regression rollback remains mandatory by default'],['Auto statuses','Yes','Open/closed only when official source is explicit','Conflicting signals are never written'],['Auto dates','Yes','Only one exact labelled date is accepted','Ambiguous/numeric-only dates are not inferred'],['Regression gate','Yes','Rollback all Stage 9 writes if release checks fail','Recommended: keep Yes'],['Resolve explicit no-change','No','Close a review when managed fields explicitly match','No keeps non-managed changes visible for later review'],['Max review items per run',STAGE9_CONFIG.DEFAULT_REVIEW_LIMIT,'Bounded source fetches per run','Prevents execution overruns'],['Max master field writes per run',STAGE9_CONFIG.DEFAULT_WRITE_LIMIT,'Bounded automatic writes','Limits blast radius'],['Retry deferred after days',STAGE9_CONFIG.DEFAULT_RETRY_DEFERRED_DAYS,'Automatic retry cadence for ambiguous items','Deferred items are not forgotten'],['Green fields','Status; Registration Opens; Registration Deadline; Submission Deadline; Application Opens; Application Deadline; Programme Start Date; Programme End Date','May auto-write with confidence >= '+STAGE9_CONFIG.AUTO_CONFIDENCE_THRESHOLD,'Official source + opportunity context + one unambiguous value'],['Amber fields','Cost; application method; location; duration; access/selectivity; source URL','Monitor/queue only','Require stronger structured extraction before future auto-enable'],['Red fields','Eligibility; school years/age; award value/coverage; Finder Eligible; deletion/removal','Never auto-write in Stage 9','High consequence / interpretation-sensitive']];sheet.getRange(1,1,rows.length,4).setValues(rows);stage9StyleHeader_(sheet,4);sheet.setFrozenRows(1);sheet.setColumnWidths(1,1,210);sheet.setColumnWidths(2,1,260);sheet.setColumnWidths(3,1,390);sheet.setColumnWidths(4,1,360);sheet.getRange(1,1,rows.length,4).setWrap(true).setVerticalAlignment('top');}
function stage9StyleHeader_(sheet,width){sheet.getRange(1,1,1,width).setBackground('#1f4e78').setFontColor('#ffffff').setFontWeight('bold').setWrap(true);}
function stage9GetPolicy_(ss){const sheet=ss.getSheetByName(STAGE9_CONFIG.SHEETS.policy);if(!sheet)return {enabled:true,autoApply:true,autoStatuses:true,autoDates:true,regressionGate:true,resolveExplicitNoChange:false,reviewLimit:STAGE9_CONFIG.DEFAULT_REVIEW_LIMIT,writeLimit:STAGE9_CONFIG.DEFAULT_WRITE_LIMIT,retryDeferredDays:STAGE9_CONFIG.DEFAULT_RETRY_DEFERRED_DAYS};const values=sheet.getRange(1,1,Math.min(sheet.getLastRow(),30),2).getDisplayValues(),map={};values.forEach(function(r){map[stage9Canon_(r[0])]=r[1];});const yes=function(k,d){return map[k]===undefined?d:/^yes|true|on|enabled$/i.test(String(map[k]).trim());},num=function(k,d,min,max){const n=Number(map[k]);return isFinite(n)?Math.max(min,Math.min(max,Math.floor(n))):d;};return {enabled:yes('enabled',true),autoApply:yes('autoapplygreenchanges',true),autoStatuses:yes('autostatuses',true),autoDates:yes('autodates',true),regressionGate:yes('regressiongate',true),resolveExplicitNoChange:yes('resolveexplicitnochange',false),reviewLimit:num('maxreviewitemsperrun',STAGE9_CONFIG.DEFAULT_REVIEW_LIMIT,1,60),writeLimit:num('maxmasterfieldwritesperrun',STAGE9_CONFIG.DEFAULT_WRITE_LIMIT,1,30),retryDeferredDays:num('retrydeferredafterdays',STAGE9_CONFIG.DEFAULT_RETRY_DEFERRED_DAYS,1,30)};}
function stage9EnsureTrigger_(){const triggers=ScriptApp.getProjectTriggers(),existing=triggers.filter(function(t){return t.getHandlerFunction()==='stage9RunDaily';});if(!existing.length)ScriptApp.newTrigger('stage9RunDaily').timeBased().everyDays(1).atHour(STAGE9_CONFIG.DAILY_HOUR).nearMinute(STAGE9_CONFIG.DAILY_MINUTE).inTimezone(STAGE9_CONFIG.TIMEZONE).create();if(existing.length>1)existing.slice(1).forEach(function(t){ScriptApp.deleteTrigger(t);});return 'daily around '+String(STAGE9_CONFIG.DAILY_HOUR).padStart(2,'0')+':'+String(STAGE9_CONFIG.DAILY_MINUTE).padStart(2,'0')+' '+STAGE9_CONFIG.TIMEZONE;}
function stage9AutoBootstrap_(){try{const props=PropertiesService.getScriptProperties();if(props.getProperty('stage9_bootstrap_version')===STAGE9_CONFIG.VERSION)return;stage9EnsureTrigger_();props.setProperty('stage9_bootstrap_version',STAGE9_CONFIG.VERSION);}catch(err){console.log('Stage 9 bootstrap deferred: '+stage9ShortError_(err));}}

function stage9SetDashboardStatus_(value,health,action){const sheet=stage9Spreadsheet_().getSheetByName(STAGE9_CONFIG.SHEETS.dashboard);if(sheet)sheet.getRange('B3:D3').setValues([[value,health,action]]);}
function stage9AppendRunLog_(r){const sheet=stage9Spreadsheet_().getSheetByName(STAGE9_CONFIG.SHEETS.runLog);if(sheet)sheet.appendRow([new Date(),r.job||'',r.kind||'all',Number(r.checked||0),0,Number(r.changes||0),0,Number(r.errors||0),Number(r.reviewItems||0),Number(r.duration||0),r.notes||'']);}
function stage9Spreadsheet_(){return SpreadsheetApp.openById(STAGE9_CONFIG.SPREADSHEET_ID);}
function stage9HeaderMap_(headers){const out={};headers.forEach(function(h,i){out[stage9Canon_(h)]=i;});return out;}
function stage9Canon_(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');}
function stage9FindHeader_(map,names){for(let i=0;i<names.length;i++){const k=stage9Canon_(names[i]);if(Object.prototype.hasOwnProperty.call(map,k))return map[k];}return -1;}
function stage9FirstHeaderValue_(row,map,names){for(let i=0;i<names.length;i++){const c=stage9FindHeader_(map,[names[i]]);if(c>=0&&String(row[c]||'').trim())return String(row[c]).trim();}return '';}
function stage9DateMs_(v){if(v instanceof Date&&!isNaN(v.getTime()))return v.getTime();const d=new Date(v||0);return isNaN(d.getTime())?0:d.getTime();}
function stage9FormatDateTime_(d){return Utilities.formatDate(d,STAGE9_CONFIG.TIMEZONE,'d MMM yyyy HH:mm');}
function stage9FormatDate_(d){return Utilities.formatDate(d,STAGE9_CONFIG.TIMEZONE,'d MMMM yyyy');}
function stage9ShortError_(e){return String(e&&e.message?e.message:e||'Unknown error').slice(0,500);}
function stage9DisplayValue_(v){return v instanceof Date?stage9FormatDate_(v):String(v===null||v===undefined?'':v);}
function stage9Equivalent_(a,b){return stage9Canon_(stage9DisplayValue_(a))===stage9Canon_(stage9DisplayValue_(b));}
function stage9EquivalentDate_(a,b){const ad=stage9AsDate_(a),bd=stage9AsDate_(b);return !!ad&&!!bd&&Utilities.formatDate(ad,STAGE9_CONFIG.TIMEZONE,'yyyy-MM-dd')===Utilities.formatDate(bd,STAGE9_CONFIG.TIMEZONE,'yyyy-MM-dd');}
function stage9AsDate_(v){if(v instanceof Date&&!isNaN(v.getTime()))return v;const s=String(v||'').trim();if(!s||/\b(tba|tbc|unknown|varies)\b/i.test(s))return null;const arr=stage9DatesInText_(s);if(arr.length===1)return arr[0].date;const d=new Date(s);return isNaN(d.getTime())?null:d;}
function stage9ReadableText_(html){let s=String(html||'');s=s.replace(/<!--[\s\S]*?-->/g,' ').replace(/<(script|style|noscript|svg|iframe)[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(p|li|div|section|article|h1|h2|h3|h4|tr)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').replace(/\n{3,}/g,'\n\n').trim();return s.slice(0,STAGE9_CONFIG.MAX_SOURCE_CHARS);}

stage9AutoBootstrap_();
